// Sign up 
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Log in
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Check username
export const CHECKUSERNAME_REQUEST = "CHECKUSERNAME_REQUEST";
export const CHECKUSERNAME_SUCCESS = "CHECKUSERNAME_SUCCESS";
export const CHECKUSERNAME_FAILURE = "CHECKUSERNAME_FAILURE";

// Check Email
export const CHECKEMAIL_REQUEST = "CHECKEMAIL_REQUEST";
export const CHECKEMAIL_SUCCESS = "CHECKEMAIL_SUCCESS";
export const CHECKEMAIL_FAILURE = "CHECKEMAIL_FAILURE";

// Check Password
export const CHECKPASSWORD_REQUEST = "CHECKPASSWORD_REQUEST";
export const CHECKPASSWORD_SUCCESS = "CHECKPASSWORD_SUCCESS";
export const CHECKPASSWORD_FAILURE = "CHECKPASSWORD_FAILURE";

// Check Dob
export const CHECKDOB_REQUEST = "CHECKDOB_REQUEST";
export const CHECKDOB_SUCCESS = "CHECKDOB_SUCCESS";
export const CHECKDOB_FAILURE = "CHECKDOB_FAILURE";

// Generate Otp
export const GENERATEOTP_REQUEST = "GENERATEOTP_REQUEST";
export const GENERATEOTP_SUCCESS = "GENERATEOTP_SUCCESS";
export const GENERATEOTP_FAILURE = "GENERATEOTP_FAILURE";

// Check Otp
export const CHECKOTP_REQUEST = "CHECKOTP_REQUEST";
export const CHECKOTP_SUCCESS = "CHECKOTP_SUCCESS";
export const CHECKOTP_FAILURE = "CHECKOTP_FAILURE";

// Verify Otp
export const VERIFYOTP_REQUEST = "VERIFYOTP_REQUEST";
export const VERIFYOTP_SUCCESS = "VERIFYOTP_SUCCESS";
export const VERIFYOTP_FAILURE = "VERIFYOTP_FAILURE";


// Create Post
export const CREATEPOST_REQUEST = "CREATEPOST_REQUEST";
export const CREATEPOST_SUCCESS = "CREATEPOST_SUCCESS";
export const CREATEPOST_FAILURE = "CREATEPOST_FAILURE";

// getAllMyPost
export const GETALLMYPOSTS_REQUEST = "GETALLMYPOSTS_REQUEST";
export const GETALLMYPOSTS_SUCCESS = "GETALLMYPOSTS_SUCCESS";
export const GETALLMYPOSTS_FAILURE = "GETALLMYPOSTS_FAILURE";

// GetFeedPost
export const GETFEEDPOSTS_REQUEST = "GETFEEDPOSTS_REQUEST";
export const GETFEEDPOSTS_SUCCESS = "GETFEEDPOSTS_SUCCESS";
export const GETFEEDPOSTS_FAILURE = "GETFEEDPOSTS_FAILURE";


// get single post
export const GETSINGLEPOST_REQUEST = "GETSINGLEPOST_REQUEST";
export const GETSINGLEPOST_SUCCESS = "GETSINGLEPOST_SUCCESS";
export const GETSINGLEPOST_FAILURE = "GETSINGLEPOST_FAILURE";

// delete post
export const DELETEPOST_REQUEST = "DELETEPOST_REQUEST";
export const DELETEPOST_SUCCESS = "DELETEPOST_SUCCESS";
export const DELETEPOST_FAILURE = "DELETEPOST_FAILURE";

// get all users
export const GETALLUSERS_REQUEST = "GETALLUSERS_REQUEST";
export const GETALLUSERS_SUCCESS = "GETALLUSERS_SUCCESS";
export const GETALLUSERS_FAILURE = "GETALLUSERS_FAILURE";

// get searched users
export const GETSEARCHEDUSERS_REQUEST = "GETSEARCHEDUSERS_REQUEST";
export const GETSEARCHEDUSERS_SUCCESS = "GETSEARCHEDUSERS_SUCCESS";
export const GETSEARCHEDUSERS_FAILURE = "GETSEARCHEDUSERS_FAILURE";

// deactivate user
export const DEACTIVATEUSER_REQUEST = "DEACTIVATEUSER_REQUEST";
export const DEACTIVATEUSER_SUCCESS = "DEACTIVATEUSER_SUCCESS";
export const DEACTIVATEUSER_FAILURE = "DEACTIVATEUSER_FAILURE";

// update user details
export const UPDATEUSERDETAILS_REQUEST = "UPDATEUSERDETAILS_REQUEST";
export const UPDATEUSERDETAILS_SUCCESS = "UPDATEUSERDETAILS_SUCCESS";
export const UPDATEUSERDETAILS_FAILURE = "UPDATEUSERDETAILS_FAILURE";

// delete user
export const DELETEUSER_REQUEST = "DELETEUSER_REQUEST";
export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const DELETEUSER_FAILURE = "DELETEUSER_FAILURE";

// checkProfile
export const CHECKPROFILE_REQUEST = "CHECKPROFILE_REQUEST";
export const CHECKPROFILE_SUCCESS = "CHECKPROFILE_SUCCESS";
export const CHECKPROFILE_FAILURE = "CHECKPROFILE_FAILURE";

// clickedProfile
export const CLICKEDPROFILE_SUCCESS = "CLICKEDPROFILE_SUCCESS";

// get logged in user

export const GETLOGGEDINUSER_REQUEST = "GETLOGGEDINUSER_REQUEST";
export const GETLOGGEDINUSER_SUCCESS = "GETLOGGEDINUSER_SUCCESS";
export const GETLOGGEDINUSER_FAILURE = "GETLOGGEDINUSER_FAILURE";

// clear feed post
export const CLEAR_FEED_POSTS = 'CLEAR_FEED_POSTS';

// update previously clicked userId
export const UPDATE_PREVIOUSLY_CLICKED_USER_ID_REQUEST = 'UPDATE_PRIVIOUSLY_CLICKED_USER_ID_REQUEST';
export const UPDATE_PREVIOUSLY_CLICKED_USER_ID_SUCCESS = 'UPDATE_PRIVIOUSLY_CLICKED_USER_ID_SUCCESS';
export const UPDATE_PREVIOUSLY_CLICKED_USER_ID_FAILURE = 'UPDATE_PRIVIOUSLY_CLICKED_USER_ID_FAILURE';

// get previously clicked userId
export const GET_PREVIOUSLY_CLICKED_USER_ID_REQUEST = 'GET_PRIVIOUSLY_CLICKED_USER_ID_REQUEST';
export const GET_PREVIOUSLY_CLICKED_USER_ID_SUCCESS = 'GET_PRIVIOUSLY_CLICKED_USER_ID_SUCCESS';
export const GET_PREVIOUSLY_CLICKED_USER_ID_FAILURE = 'GET_PRIVIOUSLY_CLICKED_USER_ID_FAILURE';


// follow user
export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE';

// unfollow user
export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

// like post
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

// unlike post
export const UNLIKE_POST_REQUEST = 'UNLIKE_POST_REQUEST';
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';
export const UNLIKE_POST_FAILURE = 'UNLIKE_POST_FAILURE';

// check-like
export const CHECK_LIKE_REQUEST = 'CHECK_LIKE_REQUEST';
export const CHECK_LIKE_SUCCESS = 'CHECK_LIKE_SUCCESS';
export const CHECK_LIKE_FAILURE = 'CHECK_LIKE_FAILURE';


